# Generated by Django 4.2 on 2024-07-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_remove_pharmmodels_pharm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmmodels',
            name='pharm_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
