name: testing
on: 
  push:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: django unit test
      run: |
        pip3 install -user django
        pip install -r requirements.txt
        python3 manage.py test
        

      
        
